#!/bin/sh

# Start the first process
{{RUN_COMMAND}} > /spidersilk_out_err 2>&1
status=$?
if [ $status -ne 0 ]; then
  echo "Failed to start {{RUN_COMMAND}}: $status"
  exit $status
fi

# This is useful when the process is daemonized, but we don't want the container to be stopped
while sleep 1; do
  #ps aux |grep {{PROCESS_WILDCARD}} |grep -q -v grep
  #PROCESS_STATUS=$?
  # If the grep above find anything, they exit with 0 status
  # If it is not 0, then something is wrong
  #if [ $PROCESS_STATUS -ne 0 ]; then
  #  exit 0
  #fi
done